In [1]:
!pip install -U scikit-learn

  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.23.2
    Uninstalling scikit-learn-0.23.2:
      Successfully uninstalled scikit-learn-0.23.2


In [3]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=0)
x = [[1,2,3],[11,12,13]]
y = [0,1]
clf.fit(x,y)

RandomForestClassifier(random_state=0)

In [5]:
clf.predict(x)

array([0, 1])

In [7]:
clf.predict([[4,5,6],[14,15,16]])

array([0, 1])

In [8]:
clf.predict([[425,556,67]])

array([1])

In [9]:
import numpy as np
rs = np.random.RandomState(10)
x = 10*rs.rand(5)
y = 2*x-1*rs.rand(5)
x.shape, y.shape

((5,), (5,))

In [14]:
rs = np.random.RandomState(10)
x = 10*rs.rand(12)
x

array([7.71320643, 0.20751949, 6.33648235, 7.48803883, 4.98507012,
       2.24796646, 1.98062865, 7.60530712, 1.69110837, 0.88339814,
       6.85359818, 9.53393346])

In [16]:
X = x.reshape(-1,3) #데이터 12개를 3행으로 바꿔줌
X

array([[7.71320643, 0.20751949, 6.33648235],
       [7.48803883, 4.98507012, 2.24796646],
       [1.98062865, 7.60530712, 1.69110837],
       [0.88339814, 6.85359818, 9.53393346]])

In [10]:
X = x.reshape(-1,1)
X.shape

(5, 1)

In [11]:
X

array([[7.71320643],
       [0.20751949],
       [6.33648235],
       [7.48803883],
       [4.98507012]])