In [18]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 15709173512006591864,
 name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 1439095195
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 1407435540424683084
 physical_device_desc: "device: 0, name: GeForce 920MX, pci bus id: 0000:01:00.0, compute capability: 5.0"]

In [2]:
import tensorflow as tf
import cProfile

In [3]:
tf.executing_eagerly()

True

In [4]:
tf.executing_eagerly()

x = [[2.]]
m = tf.matmul(x,x)
print("hello, {}".format(m))

hello,[[4.]]


In [5]:
a = tf.constant([[1,2],[3,4]])
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [6]:
tf.add(a,1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [7]:
c = tf.constant([[1,1]])

tf.add(a,c)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [11]:
print(c)

tf.Tensor([[1 1]], shape=(1, 2), dtype=int32)


In [8]:
b = tf.add(a,1)

In [9]:
print(a*b)

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [12]:
import numpy as np
#numpy 값 사용
c = np.multiply(a,b)
print(c)

[[ 2  6]
 [12 20]]


##### (동적인 제어 흐름)


In [15]:
def fizzbuzz(max_num):
    counter = tf.constant(0)
    max_num = tf.convert_to_tensor(max_num)
    for num in range(1,max_num.numpy()+1):
        num = tf.constant(num)
        if int(num%3) ==0 and int(num%5) ==0:
            print("FizzBuzz")
        elif int(num%3) ==0:
            print("Fizz")
        elif int(num%5) ==0:
            print("Buzz")
        else:
            print(num.numpy())
            
        counter +=1

In [16]:
fizzbuzz(15)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz


In [19]:
w = tf.Variable([[1.0]])
with tf.GradientTape() as tape:
    loss = w*w
    
grad = tape.gradient(loss,w)  # loss를 w로 미분하세요
print(grad)

tf.Tensor([[2.]], shape=(1, 1), dtype=float32)


In [21]:
(mnist_images, mnist_labels), _ = tf.keras.datasets.mnist.load_data()

dataset = tf.data.Dataset.from_tensor_slices(
(tf.cast(mnist_images[...,tf.newaxis]/255, tf.float32),
tf.cast(mnist_labels,tf.int64)))

dataset = dataset.shuffle(1000).batch(32)

In [23]:
mnist_images

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [24]:
mnist_images.shape  #6만건, 28*28 사이즈

(60000, 28, 28)

In [25]:
a = mnist_images[...,tf.newaxis]  #새로운 열 생성

In [26]:
a.shape

(60000, 28, 28, 1)

In [28]:
mnist_images[tf.newaxis,:,:].shape #새로운 열(앞에) 생성

(1, 60000, 28, 28)

In [29]:
mnist_images[:,tf.newaxis,:,:].shape #새로운 열(가운데에) 생성

(60000, 1, 28, 28)

In [30]:
mnist_model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(16,[3,3],activation='relu',
                          input_shape = (None,None,1)),
    tf.keras.layers.Conv2D(16,[3,3],activation='relu'),
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(10)
])

In [31]:
x = tf.Variable(10.)
checkpoint = tf.train.Checkpoint(x=x)

In [32]:
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.0>

In [33]:
x.assign(2.)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=2.0>

In [34]:
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>

In [36]:
checkpoint_path="./ckpk/"
checkpoint.save(checkpoint_path)

'./ckpk/-2'

In [37]:
x.assign(11.)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=11.0>

In [38]:
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=11.0>

In [39]:
checkpoint.restore(tf.train.latest_checkpoint(checkpoint_path))

In [40]:
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>

In [41]:
m = tf.keras.metrics.Mean('loss') #평균내기
m(0)


<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [42]:
m(5)

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [43]:
m([8,9]) #여태까지 들어온 숫자 다 평균 내줌(0+5+8+9 / 4)

<tf.Tensor: shape=(), dtype=float32, numpy=5.5>