In [1]:
import tensorflow as tf

print("tf ver = ",tf.__version__)

tf ver =  2.4.0


In [12]:
import tensorflow as tf

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(64,activation='relu'))
model.add(tf.keras.layers.Dense(64,activation='relu'))
model.add(tf.keras.layers.Dense(64,activation='softmax'))
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),loss='categorical_crossentropy',metrics=['accuracy'])

model.fit(train_data,labels,epochs=10,batch_size=32)
model.evaluate(test_data,labels)

NameError: name 'train_data' is not defined

In [4]:
model =tf.keras.Sequential([tf.keras.layers.Dense(64),tf.keras.layers.Dense(64),tf.keras.layers.Dense(10)])

In [3]:
import tensorflow as tf

x=tf.constant(1)
y=tf.constant(2)
z=tf.constant(3)

a = x*y+z

sess = tf.Session()  #Session은 tensorflow 버전 1점대에서만 사용 가능(내가 쓰는 버전은 2점대)
b=sess.run(a)

print(b)

AttributeError: module 'tensorflow' has no attribute 'Session'

In [4]:
import tensorflow as tf

x=tf.constant(1)
y=tf.constant(2)
z=tf.constant(3)

a = x*y+z
print(a)

tf.Tensor(5, shape=(), dtype=int32)


In [5]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()  
# 버전 2점대 중단하고, 1점대로 사용하기 위해 쓰는 내용

x=tf.constant(1)
y=tf.constant(2)
z=tf.constant(3)

a = x*y+z

sess = tf.Session()
b=sess.run(a)
print(b)

Instructions for updating:
non-resource variables are not supported in the long term
5


In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([[1,2],[3,4],[5,6]])

In [8]:
print(a.dtype)
print(a.shape)

<dtype: 'int32'>
(3, 2)


In [3]:
a = tf.constant([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
print(a)

tf.Tensor(
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]], shape=(6, 2), dtype=int32)


In [4]:
b = tf.reshape(a,[3,4])
b

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])>

In [5]:
c = tf.transpose(b)   #전치행렬(행과 열을 바꿔서 새로운 행렬을 만든다.)
c

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])>

In [6]:
a = tf.constant([1,2,3,4,5])
b = tf.constant([-1,-1,-1,-1,-1])
c = a*b

print(c)

tf.Tensor([-1 -2 -3 -4 -5], shape=(5,), dtype=int32)


In [10]:
a_data = [1,2,3,4,5]
b_data = [-1,-1,-1,-1,-1]

a = tf.constant(a_data)
b = tf.constant(b_data)
c = a*b

print(c)

tf.Tensor([-1 -2 -3 -4 -5], shape=(5,), dtype=int32)


In [7]:
c.numpy()

array([-1, -2, -3, -4, -5])

In [8]:
a = tf.constant([1,2,3,4,5])
b = tf.constant([1,4,6,4,9])
c = tf.equal(a,b)

print(c)

tf.Tensor([ True False False  True False], shape=(5,), dtype=bool)
