In [1]:
import tensorflow as tf
import numpy as np
#텐서는 다차원배열

In [2]:
rank_0 = tf.constant(4)
rank_0

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [3]:
print(rank_0)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
rank_1 = tf.constant([2.0,3.0,4.0])
print(rank_1)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [5]:
rank_2 = tf.constant([[1.,2.],[3.,4.],[5.,6.]],dtype=tf.float16)
print(rank_2)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [7]:
rank_3 = tf.constant([[[0,1,2,3,4],[5,6,7,8,9]],
                      [[10,11,12,13,14],[15,16,17,18,19]],
                      [[20,21,22,23,24],[25,26,27,28,29]]])

In [8]:
print(rank_3)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [9]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[1,2],[3,4]])

print(tf.add(a,b),"\n")
print(tf.multiply(a,b),"\n")
print(tf.matmul(a,b),"\n")

tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32) 



In [10]:
c= tf.constant([[4.0,5.0],[10.0,1.0]])

In [11]:
tf.reduce_max(c)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [12]:
tf.argmax(c)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 0], dtype=int64)>

In [13]:
tf.nn.softmax(c)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.6894143e-01, 7.3105854e-01],
       [9.9987662e-01, 1.2339458e-04]], dtype=float32)>

In [14]:
rank_4_tensor = tf.zeros([3,2,4,5])

In [15]:
print("Type of every element : ",rank_4_tensor.dtype)
print("Number of dimensions : ",rank_4_tensor.ndim)
print("Shape of tensor : ",rank_4_tensor.shape)

Type of every element :  <dtype: 'float32'>
Number of dimensions :  4
Shape of tensor :  (3, 2, 4, 5)


In [17]:
tf.size(rank_4_tensor).numpy()

120

In [18]:
rank_3

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])>

In [19]:
rank_3[:,:,4]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  9],
       [14, 19],
       [24, 29]])>

In [20]:
var_x = tf.Variable(tf.constant([[1],[2],[3]]))

In [23]:
var_x

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[1],
       [2],
       [3]])>

In [24]:
var_x.shape.as_list()

[3, 1]

In [25]:
reshaped = tf.reshape(var_x,[1,3])
reshaped.shape

TensorShape([1, 3])

In [26]:
print(tf.reshape(rank_3,[-1]))

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)


In [27]:
tf.reshape(rank_3,[5,6])

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])>

In [28]:
tf.reshape(rank_3,[7,-1])

InvalidArgumentError: Input to reshape is a tensor with 30 values, but the requested shape requires a multiple of 7 [Op:Reshape]

In [32]:
try:  # 에러는 건너뛰고 실행하라는 함수
    tf.reshape(rank_3,[7,-1])
except Exception as e:
    print(f"{type(e).__name__}:{e}")

InvalidArgumentError:Input to reshape is a tensor with 30 values, but the requested shape requires a multiple of 7 [Op:Reshape]


In [34]:
# sparsetensor > 희소행렬 

In [30]:
a = tf.sparse.SparseTensor(indices=[[0,0],[1,2]],values=[1,2],dense_shape=[3,4])


In [33]:
# [[1,0,0,0],  0행0열의 값 1
# [0,0,2,0],   1행2열의 값 2
# [0,0,0,0]]
#원래 이런 행렬인데 압축해서 [[0,0],[1,2]]로 나옴

In [31]:
print(a)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [ ]:
0 