In [90]:
class Dog :
    def __init__(self,name,color) :
        self.hungry = 0
        self.name = name
        self.color = color
    def eat(self) :
        self.hungry -=10
        print("밥먹음", self.hungry)
    def walk(self) :
        self.hungry +=10
        print("산책", self.hungry)

In [91]:
choco = Dog("choco","black")


In [92]:
choco.eat()

밥먹음 -10


In [17]:
class Dog :
    dog_count = 0
    
    def __init__(self,name,color):
        self.name = name
        self.color = color
        Dog.dog_count+=1
        
    def dogCount(self) :
        print("총 강아지는", Dog.dog_count)

In [18]:
hello = Dog("hello", "black")
hello.dogCount()

총 강아지는 1


In [60]:
class Car :
    carCount = 0
    
    def __init__(self,name,cc,year):
        self.__name = name
        self.__cc = cc
        self.__year = year
        Car.carCount +=1
    def get_name(self):
        print("차종은 {}입니다.".format(self.__name))
        
    def change_name(self, new_name):
        self.__name = new_name
       
    def show_cc(self):
        if self.__cc <=1000 :
            print("소형")
        elif self.__cc <=2000:  
            print("중형")
        else :
            print("대형")
            
    def get_total_cars():
        print("총 등록된 차량개수 : ", Car.carCount)

In [61]:
i30 = Car("i30", 1800,2000)
benz = Car("benz", 3000, 2015)
kia = Car("morning",900,2020)

In [62]:
hyundai.get_name()

차종은 i30입니다


In [57]:
class Car:
    carCount = 0
    
    def __init__(self, name, volume, year):
        self.__name = name
        self.__volume = volume
        self.__year = year
        Car.carCount += 1
    
    def get_name(self):
        print("차종은 {}입니다".format(self.__name))
        
    def change_name(self, new_name):
        self.__name = new_name
        
    def show_volume(self):
        if self.__volume < 1000:
            print("소형")
        elif self.__volume <= 2000:
            print("중형")
        else:
            print("대형")
    
    @classmethod
    def get_total_cars(cls):
        print("총 등록된 차량개수 : ", Car.carCount)

In [58]:
hyundai = Car("i30", 1800, 2000)
benz = Car("benz", 3000, 2015)
kia = Car("morning", 900, 2020)

In [59]:
hyundai.get_name()

차종은 i30입니다


In [33]:
class robot :
    name = "robot"
    def info(self):
        print('나의 이름은', self.name, '입니다!')


In [34]:
r = robot()

In [35]:
r.info()

나의 이름은 robot 입니다!


In [36]:
r.name

'robot'

In [37]:
isinstance(r,int)

False

In [38]:
isinstance(r,robot)

True

In [43]:
class robot :
    name = "robot"
    age = 0
    def __init__(self,name,age):
        print('생성자 호출!')
        self.name = name
        self.age = age
        
    def __del__(self):
        print('소멸자 호출!')
        
    def info(self):
        print('나의 이름은', self.name, '입니다!')
        print('나이는', self.age, '입니다!')

In [40]:
r = robot('bill',7)

생성자 호출!


In [41]:
r.info()

나의 이름은 bill 입니다!
나이는 7 입니다!


In [42]:
del r

소멸자 호출!


In [73]:
class Animal :
    def __init__(self):
        self.hungry = 0
        
    def eat(self):
        self.hungry -=10
        print("밥먹음",self.hungry)
        
    def walk(self):
        self.hungry +=10
        print("산책",self.hungry)
        

In [74]:
class Dog(Animal):
    def __init__(self):
        super().__init__()
        
    def sound(self):
        print("멍멍")

In [75]:
class Cat(Animal):
    def __init__(self):
        super().__init__()
        
    def sound(self):
        print("야옹")

In [76]:
dog = Dog()
dog.sound()

멍멍


In [77]:
dog.walk()

산책 10


In [81]:
for i in range(10,-10,-1):
    try :
        print(10/i)
    except :
        print("예외오류발생")
    

1.0
1.1111111111111112
1.25
1.4285714285714286
1.6666666666666667
2.0
2.5
3.3333333333333335
5.0
10.0
예외오류발생
-10.0
-5.0
-3.3333333333333335
-2.5
-2.0
-1.6666666666666667
-1.4285714285714286
-1.25
-1.1111111111111112


In [84]:
x = [1,2,3]

try :
    a =x[4]
except Exception as e:
    print("error : ",e)

error :  list index out of range


In [96]:
import pickle

try :
    with open("data3.p","rb") as file:
        name = pickle.load(file)
        address = pickle.load(file)
        email = pickle.load(file)
        print(name,address,email)
    
except FileNotFoundError as e :
    print("file이 존재하지 않습니다.")
    name = input("이름을 입력해주세요")
    address = input("주소을 입력해주세요")
    email = input("이메일을 입력해주세요")
    
    with open("data3.p", "wb") as file :
        pickle.dump(name, file)
        pickle.dump(address, file)
        pickle.dump(email, file)
    print("파일이 생성되었습니다.")

file이 존재하지 않습니다.
이름을 입력해주세요강다영
주소을 입력해주세요192
이메일을 입력해주세요dd@ddd
파일이 생성되었습니다.


In [1]:
import calc

print(calc.add(5,6))

11


In [2]:
from calc import add, sub
print(add(5,6))


11


In [7]:
import sys
print(sys.path)

['C:\\Users\\lenovo\\kdigital', 'C:\\Users\\lenovo\\anaconda3\\python38.zip', 'C:\\Users\\lenovo\\anaconda3\\DLLs', 'C:\\Users\\lenovo\\anaconda3\\lib', 'C:\\Users\\lenovo\\anaconda3', '', 'C:\\Users\\lenovo\\anaconda3\\lib\\site-packages', 'C:\\Users\\lenovo\\anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\lenovo\\anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\lenovo\\anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\lenovo\\anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\lenovo\\.ipython']


In [4]:
import pkcalc.calc as calc
print(calc.add(5,6))

11


In [6]:
from pkcalc.calc import add, sub
print(add(5,6))

11


In [8]:
import numpy as np

In [9]:
import pandas as pd

In [10]:
matrix_1 = [[1,2],[3,4]]
matrix_2 = [[5,6],[7,8]]

In [12]:
hap = []

for i in range(2):
    temp = []
    for j in range(2):
        print(matrix_1[i][j] + matrix_2[i][j])
        temp.append(matrix_1[i][j] + matrix_2[i][j])
    hap.append(temp)
    
print(hap)

6
8
10
12
[[6, 8], [10, 12]]


In [16]:
hap2 = []

for i in range(2):
    temp = []
    for j in range(2) :
        print(matrix_1[i][j] +1)
        temp.append(matrix_1[i][j] +1)
    hap2.append(temp)
    
print(hap2)

2
3
4
5
[[2, 3], [4, 5]]


In [18]:
matrix_1 = [[1,2],[3,4]]
matrix_2 = [[5,6],[7,8]]

In [19]:
met_sum = np.array(matrix_1) +np.array(matrix_2)
print(met_sum)

[[ 6  8]
 [10 12]]


In [20]:
met_add = np.array(matrix_1) +1
print(met_add)

[[2 3]
 [4 5]]


In [25]:
import time

size = 10000000

x = list(range(size))
y = list(range(size))





In [24]:
print(time.localtime())

time.struct_time(tm_year=2020, tm_mon=12, tm_mday=15, tm_hour=17, tm_min=22, tm_sec=17, tm_wday=1, tm_yday=350, tm_isdst=0)


In [26]:
start_time = time.time()
z = [x[i] +y[i]for i in range(size)]
print(f"리스트 걸린 시간 : {time.time()-start_time}")

리스트 걸린 시간 : 9.276077032089233


In [27]:
x = np.arange(size)
y = np.arange(size)
x

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [28]:
start_time = time.time()
z = x+y
print(print(f"넘파이 걸린 시간 : {time.time()-start_time}"))

넘파이 걸린 시간 : 1.048454761505127
None


In [29]:
x = np.uint(-32)
x

4294967264

In [35]:
x = np.uint(64)
print(x)
print(type(x))
print(x.dtype)

64
<class 'numpy.uint32'>
uint32


In [34]:
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [36]:
x =np.float32([1,2,3,4])
print(x)
print(type(x))
print(x.dtype)

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
float32


In [39]:
x = np.array([1,2,3,4],dtype = np.float32)
print(x)
print(type(x))
print(x.dtype)

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
float32


In [41]:
x = np.int32(x)
print(x.dtype)
print(x)

int32
[1 2 3 4]


In [42]:
np.issubdtype(x.dtype,np.int32)

True

In [43]:
x = np.array([1,2])

In [44]:
print(x.shape)

(2,)


In [45]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [46]:
x = x.reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [47]:
x = np.arange(24).reshape(2,3,4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [48]:
print(x.shape)

(2, 3, 4)


In [49]:
x = np.array([[1,2],[3,4],[5,6]])

In [50]:
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [51]:
print(x.reshape(2,3))

[[1 2 3]
 [4 5 6]]
