# P.155 실습 02

In [219]:
class Character : 
    def __init__(self) :
        self.health = 200
        
    def move(self) :
        self.health -=10
        
    def rest(self) :
        self.health +=10
        
    def checkHealth(self) :
        print("Health : ", self.health)

In [220]:
class Knight(Character) :
    def __init__(self) :
        super().__init__()
    
    def move(self) :
        self.health -=15
        
    def attack(self) :
        print("공격합니다")
        
    

In [221]:
knight_1 = Knight()
knight_1.checkHealth()
        

Health :  200


In [222]:
class Healer(Character) :
    def __init__(self) :
        super().__init__()
        self.mana=100
    
        
    def heal(self,character) :
        self.mana -=10
        character.rest()
        
    def checkMana(self) :
        print("현재 mana : ", self.mana)

In [215]:
healer_1 = Healer()
healer_1.checkHealth()

Health :  200


In [216]:
knight_2  = Knight()
knight_2.move()
knight_2.move()
knight_2.checkHealth()

Health :  170


In [217]:
person = Character()
person.move()
person.move()
person.checkHealth()

Health :  180


In [218]:
healer_1.checkMana()
knight_1.checkHealth()
healer_1.heal(knight_1)
healer_1.checkMana()
knight_1.checkHealth()

현재 mana :  100
Health :  200
현재 mana :  90
Health :  210


In [53]:
import numpy as np
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [54]:
x.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [55]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [56]:
print(x[1:3])

[1 2]


In [57]:
x = np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [58]:
print(x[1:3])

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [59]:
print(x[1:3, 1:3])

[[ 6  7]
 [11 12]]


In [60]:
x = np.arange(30).reshape(2,5,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [61]:
print(x[:,3:5,1])

[[10 13]
 [25 28]]


In [62]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [63]:
print(a[1][1])

6


In [64]:
np.array([[1,2],[3,4],[5,6]]).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
x = np.arange(16).reshape(2,2,2,2)
x

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [68]:
x = np.arange(30).reshape(2,5,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [69]:
print(x[:,3:5,1])

[[10 13]
 [25 28]]


In [72]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [71]:
print(a[1][1])

6


In [75]:
print(a[[1,1],[1,2]])

[6 7]


In [76]:
print(a>3)

[[False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [77]:
print(a[(a>3)&(a<8)])

[4 5 6 7]


In [78]:
np.random.rand(5,5)

array([[0.59291432, 0.24098102, 0.503398  , 0.75597355, 0.80058479],
       [0.12345102, 0.41084281, 0.32298767, 0.40069711, 0.72061327],
       [0.61136331, 0.63809395, 0.42066765, 0.61815062, 0.99516308],
       [0.51374048, 0.78345671, 0.8190413 , 0.69274079, 0.35780123],
       [0.73034778, 0.98405106, 0.82012285, 0.44153452, 0.07348295]])

In [79]:
np.random.randint(1,10)

3

In [80]:
np.random.randint(1,10,size=(5))

array([3, 9, 8, 4, 8])

In [87]:
np.random.randint(1,10,size=(5,3))

array([[1, 8, 5],
       [8, 7, 7],
       [7, 9, 4],
       [8, 4, 1],
       [3, 5, 9]])

In [88]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [89]:
x.ravel(order="C")

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [90]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [91]:
x = np.arange(1,4)

In [92]:
x

array([1, 2, 3])

In [93]:
y = np.arange(4,7)
y

array([4, 5, 6])

In [94]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [95]:
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [96]:
y = np.arange(10,20).reshape(2,5)

In [97]:
y

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [98]:
np.concatenate([x,y])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [99]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [100]:
a = np.split(x,4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [101]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [102]:
np.split(x,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [103]:
np.split(x,2,axis = 1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [105]:
x=np.array([1,2,3])
x+1

array([2, 3, 4])

In [106]:
x = np.arange(1,10).reshape(3,3)
y = np.arange(1,4)
x + y

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [110]:
x = np.array([10,20,30]).reshape(3,1)
y = np.arange(1,4)


In [111]:
print(x)
print()
print(y)

[[10]
 [20]
 [30]]

[1 2 3]


In [112]:
x+y

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [113]:
x = np.arange(4).reshape(2,2)
y = np.arange(4,8).reshape(2,2)
print(x)
print()
print(y)

[[0 1]
 [2 3]]

[[4 5]
 [6 7]]


In [114]:
x.dot(y)

array([[ 6,  7],
       [26, 31]])

In [115]:
x*y 

array([[ 0,  5],
       [12, 21]])

In [116]:
inv_x = np.linalg.inv(x)
inv_x

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [117]:
x.dot(inv_x)

array([[1., 0.],
       [0., 1.]])

In [118]:
np.linalg.det(x)

-2.0

In [119]:
np.mean(x)

1.5

In [120]:
a = np.array([10,3,-5,2,7])
np.median(a)

3.0

In [121]:
np.median(x)

1.5

In [122]:
a = np.array([10,3,-5,2,7,4])
np.median(a)

3.5

In [126]:

np.var(a)

21.583333333333332

In [125]:
np.mean(a)

3.5

In [127]:
np.var(x)

1.25

In [128]:
np.std(a)

4.645786621588784

In [129]:
np.std(x)

1.118033988749895

In [130]:
np.sum(x)

6

In [131]:
np.sum(a)

21

In [132]:
x

array([[0, 1],
       [2, 3]])

In [133]:
np.sum(x,axis =1)

array([1, 5])

In [134]:
np.sum(x,axis =0)

array([2, 4])

In [135]:
np.cumsum(x)

array([0, 1, 3, 6], dtype=int32)

In [136]:
np.cumprod(x)

array([0, 0, 0, 0], dtype=int32)

In [137]:
np.min(a)

-5

In [138]:
np.argmax(a)

0

In [139]:
np.all(x>4)

False

In [141]:
a

array([10,  3, -5,  2,  7,  4])

In [144]:
np.where(a>4)

(array([0, 4], dtype=int64),)

In [146]:
np.where(a>4,a,-100)

array([  10, -100, -100, -100,    7, -100])

In [147]:
x

array([[0, 1],
       [2, 3]])

In [148]:
np.where(x>4)

(array([], dtype=int64), array([], dtype=int64))

In [149]:
x = [1,2,3,4,5,6,7,8,9]
y = [10,20,30,40,50,60,70,80,90]


In [150]:
x = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
y = np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)

In [151]:
x+y

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [152]:
x.dot(y)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [153]:
x= np.linspace(1,20,30)
x

array([ 1.        ,  1.65517241,  2.31034483,  2.96551724,  3.62068966,
        4.27586207,  4.93103448,  5.5862069 ,  6.24137931,  6.89655172,
        7.55172414,  8.20689655,  8.86206897,  9.51724138, 10.17241379,
       10.82758621, 11.48275862, 12.13793103, 12.79310345, 13.44827586,
       14.10344828, 14.75862069, 15.4137931 , 16.06896552, 16.72413793,
       17.37931034, 18.03448276, 18.68965517, 19.34482759, 20.        ])

In [154]:
x+10

array([11.        , 11.65517241, 12.31034483, 12.96551724, 13.62068966,
       14.27586207, 14.93103448, 15.5862069 , 16.24137931, 16.89655172,
       17.55172414, 18.20689655, 18.86206897, 19.51724138, 20.17241379,
       20.82758621, 21.48275862, 22.13793103, 22.79310345, 23.44827586,
       24.10344828, 24.75862069, 25.4137931 , 26.06896552, 26.72413793,
       27.37931034, 28.03448276, 28.68965517, 29.34482759, 30.        ])

In [165]:
x = np.random.randint(1,101,size=(2,10,10))

In [166]:
x

array([[[ 70,  98,  72,  80,  17,  48,  26,  81,  26,  61],
        [ 88,  20,  89,  62,   9,  26,  41,   1,  43,  47],
        [  2,  99,  77,   4,  78,   5,  13,  26,  79,  50],
        [ 50,   2,  80,  55,  53,  59,  85,  53,  39,  58],
        [ 56,  13,  71,  49,   4,  97,  54,  52,   8,  95],
        [  1,  30,  28,   1,  78,  52,  20,  98,  16,  28],
        [ 84,  87,  22,  67,   1,  64,  45,  88,  40,   9],
        [ 88,  71,  87,  74,  54,  32,  14,  81,  90,  88],
        [ 52,  79,  23,  79,   1,  93,  14,  82,  26,  93],
        [ 73,  82,  50,  47,  39,  23,   7,  97,  20,  43]],

       [[ 18,  39,  49,  96,  46,  37,  20,  44,  86,  62],
        [ 22,  68,  75,  75,  10,  80,  17,  57,   1,  50],
        [ 34,  87,  47,  54,  66,  59,  80,  67,  40,  58],
        [ 80,  61,  97,  56,  75,  88,  22,  30,  97,  83],
        [  7,  39, 100,  42,  63,  77,  80,  35,  47,  99],
        [ 68,  16,  32,  12,  99,  57,  87, 100,  54,  26],
        [ 33,  35,  44,  89,  77,  83,

In [171]:
np.where(x>=50,1,2)

array([[[1, 1, 1, 1, 2, 2, 2, 1, 2, 1],
        [1, 2, 1, 1, 2, 2, 2, 2, 2, 2],
        [2, 1, 1, 2, 1, 2, 2, 2, 1, 1],
        [1, 2, 1, 1, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 2, 2, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 1, 1, 2, 1, 2, 2],
        [1, 1, 2, 1, 2, 1, 2, 1, 2, 2],
        [1, 1, 1, 1, 1, 2, 2, 1, 1, 1],
        [1, 1, 2, 1, 2, 1, 2, 1, 2, 1],
        [1, 1, 1, 2, 2, 2, 2, 1, 2, 2]],

       [[2, 2, 2, 1, 2, 2, 2, 2, 1, 1],
        [2, 1, 1, 1, 2, 1, 2, 1, 2, 1],
        [2, 1, 2, 1, 1, 1, 1, 1, 2, 1],
        [1, 1, 1, 1, 1, 1, 2, 2, 1, 1],
        [2, 2, 1, 2, 1, 1, 1, 2, 2, 1],
        [1, 2, 2, 2, 1, 1, 1, 1, 1, 2],
        [2, 2, 2, 1, 1, 1, 1, 1, 1, 2],
        [1, 1, 2, 2, 1, 2, 2, 1, 2, 2],
        [1, 2, 1, 1, 2, 2, 1, 1, 1, 2],
        [1, 2, 2, 1, 2, 1, 1, 2, 2, 1]]])

In [173]:
x= np.where(x>=50,1,2)
print(x[1,5:10,5:10])

[[1 1 1 1 2]
 [1 1 1 1 2]
 [2 2 1 2 2]
 [2 1 1 1 2]
 [1 1 2 2 1]]


In [174]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [175]:
np.where(a>4)


(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [176]:
import pandas as pd

In [177]:
x = [1,2,3,4,5]
s = pd.Series(x)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [178]:
print(s.index)

RangeIndex(start=0, stop=5, step=1)


In [179]:
s.values

array([1, 2, 3, 4, 5], dtype=int64)

In [180]:
type(s.values)

numpy.ndarray

In [181]:
s = pd.Series(x,index=['a','b','c','d','e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [182]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [183]:
s['c']

3

In [184]:
s[['b','d']]

b    2
d    4
dtype: int64

In [185]:
s[[0,3]]

a    1
d    4
dtype: int64

In [186]:
s.a

1

In [187]:
x = {"수학" : 90, "영어" : 80, "과학" : 95, "미술" : 80}
x = pd.Series(x)
x

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [189]:
x.index

Index(['수학', '영어', '과학', '미술'], dtype='object')

In [190]:
x['수학']

90

In [193]:
x['영어' : ]

영어    80
과학    95
미술    80
dtype: int64

In [194]:
x['영어' : '미술']

영어    80
과학    95
미술    80
dtype: int64

In [195]:
x

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [196]:
part = pd.Series(x, index=["수학", "영어", "과학"])

In [197]:
part

수학    90
영어    80
과학    95
dtype: int64

In [198]:
student_1 = {"수학" : 90, "영어":80, "과학" : 95, "미술" : 80}
student_2 = {"수학" : 70, "영어":90, "과학" : 100, "미술" : 70}

In [200]:
index = ["홍길동" for i in range(len(student_1))] + ["이몽룡" for i in range(len(student_2))]


In [201]:
index2 = list(student_1.keys()) + list(student_2.keys())
index2

['수학', '영어', '과학', '미술', '수학', '영어', '과학', '미술']

In [202]:
value_all = list(student_1.values()) + list(student_2.values())
value_all

[90, 80, 95, 80, 70, 90, 100, 70]

In [203]:
students = pd.Series(value_all, index = [index,index2])

In [204]:
students

홍길동  수학     90
     영어     80
     과학     95
     미술     80
이몽룡  수학     70
     영어     90
     과학    100
     미술     70
dtype: int64

In [206]:
students['홍길동']['수학']

90

In [207]:
students['홍길동']

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [208]:
students

KeyError: '이몽룡'