In [1]:
2/3 #나누는 것

0.6666666666666666

In [2]:
2//3 # 몫

0

In [3]:
2%3 # 나머지

2

In [4]:
2**2 #제곱

4

In [7]:
0b10111 #이진수

23

In [6]:
bin(23)

'0b10111'

In [9]:
oct(12)  #8진수

'0o14'

In [10]:
hex(35) #10진수

'0x23'

In [13]:
a = (1,2,3) #튜플
b = [2,3,4] #리스트
e = [4,5,6]
c = {3,4,5} #set(집합)
d = {'a':1,'b':2} #딕셔너리

In [12]:
print('a'+'b')

ab


In [17]:
# append
# extend
# b.append(object) : 덩어리 안에 값 object(appned했을 때 덩어리가 한번에 들어감)
# b.extend(iterable) : (append하면 iterable은 값이 하나씩 들어간다.)
# b.insert(index,object) : index(몇 번째 자리에), object(무슨값)을 넣겠다는 뜻

In [15]:
b.append(e)

In [16]:
b

[2, 3, 4, [4, 5, 6]]

### 1번 문제
- 시저는 '20210202 venice attack' -> 클레오파트라 전송
- 시저암호
- 시저는 암호화
- 클레오파트라는 복호화

In [60]:
code = '20210202 venice attack'

In [100]:
nc = code.split(" ")
nc

['20210202', 'venice', 'attack']

In [62]:
nc[0]
nc_1 = list(nc[0])
nc_1

['2', '0', '2', '1', '0', '2', '0', '2']

In [63]:
for i in range(len(nc_1)):
    nc_1[i] = int(nc_1[i])+3
print(nc_1)   

[5, 3, 5, 4, 3, 5, 3, 5]


In [86]:
nc[1]
nc_2 = list(nc[1])
nc_2

['v', 'e', 'n', 'i', 'c', 'e']

In [117]:
for e in nc_2:
    #print(e)
    print(chr(ord(e)+3))
#     no = ord(str(nc_2[e]))+3
#     en = chr(no)
#print(en)

y
h
q
l
f
h


In [101]:
nc[2]
nc_3 = list(nc[2])
nc_3

['a', 't', 't', 'a', 'c', 'k']

In [103]:
for w in nc_3:
    print(chr(ord(w)+3))

d
w
w
d
f
n


In [38]:
for i in range(97,123):
    print(chr(i), end=' ')  # chr는 숫자를 문자로 바꿈
                            # ord는 문자를 숫자로 바꿈

a b c d e f g h i j k l m n o p q r s t u v w x y z 

In [133]:
newlist = []
def switch(a):
    for w in a:
        b = chr(ord(w)+3)
        newlist.append(b)
    return newlist
a = 'venice attack'

In [134]:
switch(a)

['y', 'h', 'q', 'l', 'f', 'h', '#', 'd', 'w', 'w', 'd', 'f', 'n']

### 2번문제, 4번문제
- 369 문제

In [198]:
mul = list(range(0,101))

In [175]:
print(mul)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


In [172]:
multi = list(map(str,mul))

In [173]:
multi

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '70',
 '71',
 '72',
 '73',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '80',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '90',
 '91',
 '92',
 '93',
 '94',
 '95',
 '96',
 '97',
 '98',
 '99',
 '100']

In [149]:
if multi[16] == '6':
    print('짝')
multi[16]

'16'

In [208]:
for q in range(len(mul)):
    if mul[q] % 10 == 3:
        print("짝")
    elif mul[q] % 10 ==6:
        print("짝")
    elif mul[q] % 10 ==9:
        print("짝")
    #elif mul[q]==range(30,40):
     #   print("짝짝")
    else :
        print(q)

0
1
2
짝
4
5
짝
7
8
짝
10
11
12
짝
14
15
짝
17
18
짝
20
21
22
짝
24
25
짝
27
28
짝
30
31
32
짝
34
35
짝
37
38
짝
40
41
42
짝
44
45
짝
47
48
짝
50
51
52
짝
54
55
짝
57
58
짝
60
61
62
짝
64
65
짝
67
68
짝
70
71
72
짝
74
75
짝
77
78
짝
80
81
82
짝
84
85
짝
87
88
짝
90
91
92
짝
94
95
짝
97
98
짝
100


In [209]:
qw = list(range(0,101))

In [210]:
qw

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [225]:
############ 369 중요한 부분 #####################

for u in range(len(qw)):
    if qw[u] % 10 == 3 or qw[u] % 10 == 6 or qw[u] % 10 == 9:
        if qw[u] // 10 ==3 or qw[u] // 10 ==6 or qw[u] // 10 ==9:
            print("짝짝")
        else:
            print("짝")
    elif qw[u] // 10 ==3 or qw[u] // 10 ==6 or qw[u] // 10 ==9:
        print("짝")
    else:
        print(u)

0
1
2
짝
4
5
짝
7
8
짝
10
11
12
짝
14
15
짝
17
18
짝
20
21
22
짝
24
25
짝
27
28
짝
짝
짝
짝
짝짝
짝
짝
짝짝
짝
짝
짝짝
40
41
42
짝
44
45
짝
47
48
짝
50
51
52
짝
54
55
짝
57
58
짝
짝
짝
짝
짝짝
짝
짝
짝짝
짝
짝
짝짝
70
71
72
짝
74
75
짝
77
78
짝
80
81
82
짝
84
85
짝
87
88
짝
짝
짝
짝
짝짝
짝
짝
짝짝
짝
짝
짝짝
100


In [157]:
# for i in range(len(multi)):
#     if multi[i]>10:
#     if multi[i].find('3') :
#         print(multi[i])
#     else :
#         print('짝')

TypeError: '>' not supported between instances of 'str' and 'int'

In [200]:
li = []
for w in range(len(mul)):
    tq1=str(mul[w])
    r = tq1.split()
    print(r)
    #li.append(r)
#print(li)

['0']
['1']
['2']
['3']
['4']
['5']
['6']
['7']
['8']
['9']
['10']
['11']
['12']
['13']
['14']
['15']
['16']
['17']
['18']
['19']
['20']
['21']
['22']
['23']
['24']
['25']
['26']
['27']
['28']
['29']
['30']
['31']
['32']
['33']
['34']
['35']
['36']
['37']
['38']
['39']
['40']
['41']
['42']
['43']
['44']
['45']
['46']
['47']
['48']
['49']
['50']
['51']
['52']
['53']
['54']
['55']
['56']
['57']
['58']
['59']
['60']
['61']
['62']
['63']
['64']
['65']
['66']
['67']
['68']
['69']
['70']
['71']
['72']
['73']
['74']
['75']
['76']
['77']
['78']
['79']
['80']
['81']
['82']
['83']
['84']
['85']
['86']
['87']
['88']
['89']
['90']
['91']
['92']
['93']
['94']
['95']
['96']
['97']
['98']
['99']
['100']


### 3번문제(KTX)

In [226]:
import numpy as np

In [227]:
list1 =[]
a=np.array(list1)

In [229]:
print(a)

[]


In [230]:
a = np.zeros((4,13))

In [244]:
a1 = np.empty((4,13))

In [245]:
print(a1)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [231]:
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [246]:
emptyli = []
for c in range(1,14):
    emptyli.append(' ')
emptyli

[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']

In [248]:
ktx = np.array([y,emptyli,emptyli,x])

In [249]:
ktx

array([['A', 'C', 'E', 'G', 'I', 'K', 'M', 'O', 'Q', 'S', 'U', 'W', 'Y'],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       ['B', 'D', 'F', 'H', 'J', 'L', 'N', 'P', 'R', 'T', 'V', 'X', 'Z']],
      dtype='<U1')

In [235]:
#chr(65)
chr(90)

'Z'

In [237]:
y = []
x = []
for z in range(65,91):
    if z % 2 ==1 :
        y.append(chr(z))
    else :
        x.append(chr(z))    

In [238]:
y

['A', 'C', 'E', 'G', 'I', 'K', 'M', 'O', 'Q', 'S', 'U', 'W', 'Y']

In [239]:
x

['B', 'D', 'F', 'H', 'J', 'L', 'N', 'P', 'R', 'T', 'V', 'X', 'Z']

In [240]:
# def coco(text,num):
#     password=''
#     for i in range(len(text)):
#         a=ord(text[i])
#         password +=chr(a+num)
#     return password
# text = "20210202 venice attack"
# print(coco(text,3))
# print(coco(coco(text,3),-3))

53543535#yhqlfh#dwwdfn
20210202 venice attack
